---
name: Test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: >
          Run the build with tmate debugging enabled
          (https://github.com/marketplace/actions/debugging-with-tmate)
        required: false
        default: false
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          # Quoting is necessary as otherwise the value is interpreted as a
          # number, which could truncate digits.
          # https://github.com/actions/setup-python/issues/160
          python-version: "3.11"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        # Single quotes required otherwise GitHub actions throws
        # 'Unexpected symbol' error.
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}

      - name: Run project setup
        run: |
          python -m pip install --upgrade "pip"
          python -m pip install \
            --requirement "./requirements.txt" \
            --requirement "./dev-requirements.txt"

      - name: Run tests
        run: |
          make test
