---
name: Test

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        description: >
          Run the build with tmate debugging enabled
          (https://github.com/marketplace/actions/debugging-with-tmate)
        required: false
        default: false
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}

      - name: Install poetry
        run: python -m pip install poetry

      - name: Run project setup
        run: poetry install --no-root

      - name: Run tests
        run: |
          export CONTAINER_NAME="jenkins-torkel"
          export DOCKER_REPO="cavcrosby/jenkins-torkel"
          export DOCKER_CONTEXT_TAG="test"

          docker build --tag "${DOCKER_REPO}:${DOCKER_CONTEXT_TAG}" "${PWD}"
          poetry run python -m unittest --verbose
